AWSTemplateFormatVersion: '2010-09-09'
Description: Layer 2 - Security Groups (My IP Only + EIC SG Reference)

Parameters:
  MyIpAddress:
    Type: String
    Description: "접속을 허용할 관리자 IP"
    AllowedPattern: '^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/\d{1,2}$'

  # [삭제됨] VpcCidr 파라미터는 더 이상 필요 없습니다. (SG 참조 방식 사용)

Resources:
  # ---------------------------------------------------
  # 1. 외부 로드밸런서(ALB)용 SG
  # ---------------------------------------------------
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Public ALB Access (Restricted to My IP)
      VpcId: !ImportValue Osaka-3Tier-VpcId
      SecurityGroupIngress:
        # [HTTP 80] 사용자님 IP만 허용
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref MyIpAddress
        # [HTTPS 443] 사용자님 IP만 허용
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref MyIpAddress

  # ---------------------------------------------------
  # 2. Web 서버용 SG
  # ---------------------------------------------------
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web Tier Access
      VpcId: !ImportValue Osaka-3Tier-VpcId
      SecurityGroupIngress:
        # [서비스] 외부 ALB에서 오는 트래픽만 받음
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        
        # [관리] EIC 보안 그룹에서의 SSH 접속만 허용 (보안 강화!)
        # IP 대역이 아니라 'EIC 딱지'가 붙은 트래픽만 통과시킴
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !ImportValue Osaka-3Tier-EICSG

  # ---------------------------------------------------
  # 3. 내부 로드밸런서(Internal ALB)용 SG
  # ---------------------------------------------------
  InternalALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Internal ALB Access
      VpcId: !ImportValue Osaka-3Tier-VpcId
      SecurityGroupIngress:
        # [서비스] Web 서버에서 오는 트래픽만 받음
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref WebSecurityGroup

  # ---------------------------------------------------
  # 4. App 서버(WAS)용 SG
  # ---------------------------------------------------
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: App Tier Access
      VpcId: !ImportValue Osaka-3Tier-VpcId
      SecurityGroupIngress:
        # [서비스] 내부 ALB에서 오는 트래픽만 받음
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref InternalALBSecurityGroup
        
        # [관리] EIC 보안 그룹에서의 SSH 접속만 허용
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !ImportValue Osaka-3Tier-EICSG

  # ---------------------------------------------------
  # 5. DB 서버(RDS)용 SG
  # ---------------------------------------------------
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Database Access
      VpcId: !ImportValue Osaka-3Tier-VpcId
      SecurityGroupIngress:
        # [서비스] App 서버에서 오는 DB 접속(3306)만 받음
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AppSecurityGroup
        
        # [확인] RDS는 SSH 접속 불가하므로 22번 규칙 없음 (잘 하셨습니다!)

Outputs:
  ALBSG:
    Value: !Ref ALBSecurityGroup
    Export: { Name: Osaka-3Tier-ALBSG }
  WebSG:
    Value: !Ref WebSecurityGroup
    Export: { Name: Osaka-3Tier-WebSG }
  InternalALBSG:
    Value: !Ref InternalALBSecurityGroup
    Export: { Name: Osaka-3Tier-InternalALBSG }
  AppSG:
    Value: !Ref AppSecurityGroup
    Export: { Name: Osaka-3Tier-AppSG }
  DBSG:
    Value: !Ref DBSecurityGroup
    Export: { Name: Osaka-3Tier-DBSG }